### ISSUE TITLE
No address associated with hostname error while trying to run container

### ISSUE THREAD

**Issue by MikhailLukashevich** [DmitryUlyanov/deep-image-prior#50]
I try to start container by running command `nvidia-docker run --rm -it --ipc=host -p 8888:8888 deep-image-prior` and it throws the following error. Any idea about it ??? 
<pre>[I 18:44:33.866 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 18:44:33.876 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 864, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/opt/miniconda/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</opt/miniconda/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/opt/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1628, in initialize
    self.init_webapp()
  File "/opt/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/opt/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/opt/miniconda/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/miniconda/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/opt/miniconda/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname</pre>

**Comment by Edwardmark** [comment]
@DmitryUlyanov @MikhailLukashevich I met the same error, any clue?

**Comment by H3llK33p3r** [comment]
+1

**Comment by cesarandreslopez** [comment]
+1

**Comment by vaadhoo** [comment]
+1

**Comment by zigit** [comment]
nvidia-docker run --rm -it --hostname prior --name prior --ipc=host  -p 8888:8888 deep-image-prior jupyter notebook --ip="0.0.0.0" --no-browser --allow-root

**Comment by H3llK33p3r** [comment]
@zigit Thank you :) !

**Comment by TDteach** [comment]
+1

**Comment by mehraveh2016** [comment]
I used 
nvidia-docker run --rm -it --ipc=host -p 8888:8888 deep-image-prior jupyter notebook --ip="0.0.0.0" --no-browser --allow-root
but gives me and error :
 

 File "<ipython-input-8-d8cc3bd386a7>", line 1
    nvidia-docker run --rm -it --ipc=host -p 8888:8888 deep-image-prior jupyter notebook --ip="0.0.0.0" --no-browser --allow-root
                    ^
SyntaxError: invalid syntax

can anybody help me  please ?
