### ISSUE TITLE
 some problem of the code

### ISSUE THREAD

**Issue by fengyayuan** [DmitryUlyanov/deep-image-prior#60]
hello,
I couldn‘t run the code of "restoration".I had this problem when I run "restoration":name 'Concat' is not defined.(the "concat" from the "skip.py").
My python and pytorch versions are 3.6 and 0.4,but i couldn't run the code successfully.Anybody know how to solve this problem?Thank you.

**Comment by fengyayuan** [comment]
Traceback (most recent call last):

  File "<ipython-input-37-899a677b9cc7>", line 1, in <module>
    runfile('C:/Users/57680/image/restoration.py', wdir='C:/Users/57680/image')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/57680/image/restoration.py", line 90, in <module>
    upsample_mode='bilinear').type(dtype)

  File "C:\Users\57680\image\model\__init__.py", line 17, in get_net
    need_sigmoid=True, need_bias=True, pad=pad, act_fun=act_fun)

  File "C:\Users\57680\image\model\skip.py", line 52, in skip
    model_tmp.add(Concat(1, skip, deeper))

NameError: name 'Concat' is not defined
